import { LegalPageLayout } from "@/components/legal/legal-page-layout";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service | NEXA AI",
  description: "Read the terms and conditions for using NEXA AI trading signal services.",
};

export default function TermsPage() {
  return (
    <LegalPageLayout title="Terms of Service" lastUpdated="January 2024">
      <div className="space-y-8">
        <section>
          <h2 className="text-2xl font-bold mb-4 text-foreground">1. Acceptance of Terms</h2>
          <p className="text-muted-foreground leading-relaxed">
            By accessing and using NEXA AI services through moulaytrading.fit, you agree to be bound by 
            these Terms of Service. If you do not agree to these terms, please do not use our services. 
            We reserve the right to modify these terms at any time, and your continued use constitutes 
            acceptance of any changes.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold mb-4 text-foreground">2. Service Description</h2>
          <p className="text-muted-foreground leading-relaxed mb-4">
            NEXA AI provides AI-powered trading signals for:
          </p>
          <ul className="list-disc pl-6 space-y-2 text-muted-foreground">
            <li>Foreign Exchange (Forex) markets</li>
            <li>Gold (XAU/USD)</li>
            <li>Cryptocurrencies (BTC, ETH, and others)</li>
          </ul>
          <p className="text-muted-foreground leading-relaxed mt-4">
            Signals are delivered via private Telegram channels and include entry prices, stop loss levels, 
            and take profit targets. These signals are generated by our proprietary AI algorithms and are 
            for informational purposes only.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold mb-4 text-foreground">3. Eligibility</h2>
          <p className="text-muted-foreground leading-relaxed">
            You must be at least 18 years old and legally capable of entering into binding contracts to use 
            our services. By using NEXA AI, you represent that you meet these requirements. Trading may not 
            be legal in all jurisdictions - it is your responsibility to ensure compliance with local laws.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold mb-4 text-foreground">4. Account Registration</h2>
          <p className="text-muted-foreground leading-relaxed">
            To access our premium services, you must provide accurate information during registration. You 
            are responsible for maintaining the confidentiality of your account credentials and for all 
            activities under your account. Notify us immediately of any unauthorized access.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold mb-4 text-foreground">5. Subscription and Payment</h2>
          <h3 className="text-xl font-semibold mb-3 text-foreground">5.1 Pricing</h3>
          <p className="text-muted-foreground leading-relaxed mb-4">
            Subscription plans are offered at prices displayed on our pricing page. All prices are in USD 
            unless otherwise stated.
          </p>
          
          <h3 className="text-xl font-semibold mb-3 text-foreground">5.2 Payment Methods</h3>
          <p className="text-muted-foreground leading-relaxed mb-4">
            We accept payments via PayPal and cryptocurrencies (BTC, ETH, USDT). Cryptocurrency payments 
            are processed on their respective blockchain networks.
          </p>
          
          <h3 className="text-xl font-semibold mb-3 text-foreground">5.3 Billing Cycle</h3>
          <p className="text-muted-foreground leading-relaxed">
            Subscriptions are billed according to the selected plan (weekly, monthly, quarterly, or annual). 
            Access begins immediately upon payment confirmation.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold mb-4 text-foreground">6. Free Trial</h2>
          <p className="text-muted-foreground leading-relaxed">
            We offer a 7-day free trial for new users. The trial provides access to our basic signal 
            features. No payment information is required for the trial. After the trial period, you must 
            subscribe to continue receiving signals.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold mb-4 text-foreground">7. Intellectual Property</h2>
          <p className="text-muted-foreground leading-relaxed">
            All content on NEXA AI, including but not limited to trading signals, algorithms, website 
            design, text, graphics, and logos, are the exclusive property of NEXA AI and protected by 
            intellectual property laws. You may not reproduce, distribute, or create derivative works 
            without our express written consent.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold mb-4 text-foreground">8. Prohibited Activities</h2>
          <p className="text-muted-foreground leading-relaxed mb-4">
            You agree not to:
          </p>
          <ul className="list-disc pl-6 space-y-2 text-muted-foreground">
            <li>Share or redistribute trading signals to non-subscribers</li>
            <li>Attempt to reverse-engineer our AI algorithms</li>
            <li>Use automated systems to access our services</li>
            <li>Violate any applicable laws or regulations</li>
            <li>Engage in any activity that disrupts our services</li>
            <li>Create multiple accounts to abuse free trials</li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-bold mb-4 text-foreground">9. Disclaimer of Warranties</h2>
          <p className="text-muted-foreground leading-relaxed">
            NEXA AI services are provided &quot;as is&quot; without warranties of any kind. We do not guarantee 
            the accuracy, completeness, or profitability of our trading signals. Past performance does 
            not guarantee future results. Trading involves substantial risk of loss.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold mb-4 text-foreground">10. Limitation of Liability</h2>
          <p className="text-muted-foreground leading-relaxed">
            To the maximum extent permitted by law, NEXA AI shall not be liable for any indirect, 
            incidental, special, consequential, or punitive damages, including but not limited to 
            loss of profits, trading losses, or data, arising from your use of our services.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold mb-4 text-foreground">11. Termination</h2>
          <p className="text-muted-foreground leading-relaxed">
            We reserve the right to suspend or terminate your account at any time for violation of 
            these terms or for any other reason at our sole discretion. Upon termination, your access 
            to premium features will cease immediately.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold mb-4 text-foreground">12. Governing Law</h2>
          <p className="text-muted-foreground leading-relaxed">
            These terms shall be governed by and construed in accordance with applicable international 
            laws. Any disputes shall be resolved through binding arbitration.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold mb-4 text-foreground">13. Contact Information</h2>
          <p className="text-muted-foreground leading-relaxed">
            For questions about these Terms of Service, contact us at:
          </p>
          <ul className="list-none mt-4 space-y-2 text-muted-foreground">
            <li>Email: support@moulaytrading.fit</li>
            <li>Telegram: @NexaAI_Support</li>
          </ul>
        </section>
      </div>
    </LegalPageLayout>
  );
}
